apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml

commonLabels:
  app.kubernetes.io/part-of: external-monitoring

# Add cluster identifier label to all resources
labels:
  - pairs:
      cluster: k8s-nixos
    includeSelectors: false
